In [1]:

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
#dataset
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

#train-Test Split

df.iloc[:, 1:] → all columns except the first → features (X)
df.iloc[:, 0] → first column → target (y)
test_size=0.2 → 20% test data and 80% training data.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

#Scaling

Calculates the mean and standard deviation from training data and scales it.
scaled value = (value - mean) / standard deviation

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.91329435, -0.16697907, -0.89601682, ..., -0.53669175,
        -1.11831132, -0.38968335],
       [-0.74774019, -0.20038118, -0.772085  , ..., -0.74521466,
        -0.29819399, -1.10597679],
       [-0.75660916, -0.77776046, -0.78323458, ..., -0.74459359,
        -0.11203239,  0.20348816],
       ...,
       [-0.70930797,  2.38589624, -0.70390106, ..., -0.70003211,
        -0.05668705, -0.68425543],
       [ 1.67348943,  0.46766096,  1.66023775, ...,  2.01169727,
         1.16594185,  0.20061148],
       [-0.74182754, -0.12880524, -0.76951202, ..., -0.78061542,
         0.65106247, -0.79011727]])

In [9]:
y_train

405    B
251    B
348    B
286    B
219    M
      ..
296    B
125    B
456    B
2      M
55     B
Name: diagnosis, Length: 455, dtype: object

#Label Encoding

In [10]:
encoder = LabelEncoder(). #Creates a label encoder.
y_train = encoder.fit_transform(y_train) #Converts labels
y_test = encoder.transform(y_test) #Converts test labels using the same mapping.

SyntaxError: invalid syntax (74467037.py, line 1)

In [ ]:
y_train

#Numpy Arrays To Pytorch Tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32)) #Converts training features from NumPy array to PyTorch tensor.
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))   #Converts test features to a PyTorch tensor.
y_train_tensor = torch.from_numpy(y_train.astype(np.float32)) #Converts training labels to PyTorch tensor.
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))   #Converts test labels to PyTorch tensor.

In [ ]:
X_train_tensor.shape #Shows the shape of training features.

In [ ]:
y_train_tensor.shape #Shows the shape of training labels.

#Defining The Model

In [ ]:
#create model class
import torch.nn as nn #nn module


class MySimpleNN(nn.Module):

  def __init__(self, num_features):           #constructor ,num_features-featureswill come in nn at input time

    super().__init__()                       #invoke Parent class constructor [child class constructor call parent class constructor through super keyword]
    self.linear = nn.Linear(num_features, 1) #linear layer (how much features comes in i/p ,hpw much features going as output)
    self.sigmoid = nn.Sigmoid()              #Activation Function

  def forward(self, features):               #forward pass
    out = self.linear(features)              #z=wx
    out = self.sigmoid(out)

    return out

In [ ]:
model.linear.weight
model.linear.bias

#Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# define loss function
loss_function = nn.BCELoss()  #binnary class entrophy class

#Training Pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1)) #view=reshape

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

In [ ]:
model.linear.weight

#Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')